// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: output.proto

public final class Output {
  private Output() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LEDOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LEDOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool on = 1;</code>
     *
     * <pre>
     * required
     * </pre>
     */
    boolean hasOn();
    /**
     * <code>optional bool on = 1;</code>
     *
     * <pre>
     * required
     * </pre>
     */
    boolean getOn();
  }
  /**
   * Protobuf type {@code LEDOutput}
   *
   * <pre>
   * A message for controlling an LED
   * </pre>
   */
  public static final class LEDOutput extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LEDOutput)
      LEDOutputOrBuilder {
    // Use LEDOutput.newBuilder() to construct.
    private LEDOutput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LEDOutput(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LEDOutput defaultInstance;
    public static LEDOutput getDefaultInstance() {
      return defaultInstance;
    }

    public LEDOutput getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LEDOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              on_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Output.internal_static_LEDOutput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Output.internal_static_LEDOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Output.LEDOutput.class, Output.LEDOutput.Builder.class);
    }

    public static com.google.protobuf.Parser<LEDOutput> PARSER =
        new com.google.protobuf.AbstractParser<LEDOutput>() {
      public LEDOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LEDOutput(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LEDOutput> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ON_FIELD_NUMBER = 1;
    private boolean on_;
    /**
     * <code>optional bool on = 1;</code>
     *
     * <pre>
     * required
     * </pre>
     */
    public boolean hasOn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool on = 1;</code>
     *
     * <pre>
     * required
     * </pre>
     */
    public boolean getOn() {
      return on_;
    }

    private void initFields() {
      on_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, on_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, on_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Output.LEDOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Output.LEDOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Output.LEDOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Output.LEDOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Output.LEDOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Output.LEDOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Output.LEDOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Output.LEDOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Output.LEDOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Output.LEDOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Output.LEDOutput prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LEDOutput}
     *
     * <pre>
     * A message for controlling an LED
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LEDOutput)
        Output.LEDOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Output.internal_static_LEDOutput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Output.internal_static_LEDOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Output.LEDOutput.class, Output.LEDOutput.Builder.class);
      }

      // Construct using Output.LEDOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        on_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Output.internal_static_LEDOutput_descriptor;
      }

      public Output.LEDOutput getDefaultInstanceForType() {
        return Output.LEDOutput.getDefaultInstance();
      }

      public Output.LEDOutput build() {
        Output.LEDOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Output.LEDOutput buildPartial() {
        Output.LEDOutput result = new Output.LEDOutput(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.on_ = on_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Output.LEDOutput) {
          return mergeFrom((Output.LEDOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Output.LEDOutput other) {
        if (other == Output.LEDOutput.getDefaultInstance()) return this;
        if (other.hasOn()) {
          setOn(other.getOn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Output.LEDOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Output.LEDOutput) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean on_ ;
      /**
       * <code>optional bool on = 1;</code>
       *
       * <pre>
       * required
       * </pre>
       */
      public boolean hasOn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool on = 1;</code>
       *
       * <pre>
       * required
       * </pre>
       */
      public boolean getOn() {
        return on_;
      }
      /**
       * <code>optional bool on = 1;</code>
       *
       * <pre>
       * required
       * </pre>
       */
      public Builder setOn(boolean value) {
        bitField0_ |= 0x00000001;
        on_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool on = 1;</code>
       *
       * <pre>
       * required
       * </pre>
       */
      public Builder clearOn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        on_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LEDOutput)
    }

    static {
      defaultInstance = new LEDOutput(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LEDOutput)
  }

  public interface DroneOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DroneOutput)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code DroneOutput}
   *
   * <pre>
   * A message for controlling a A.R. Drone
   * </pre>
   */
  public static final class DroneOutput extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DroneOutput)
      DroneOutputOrBuilder {
    // Use DroneOutput.newBuilder() to construct.
    private DroneOutput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DroneOutput(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DroneOutput defaultInstance;
    public static DroneOutput getDefaultInstance() {
      return defaultInstance;
    }

    public DroneOutput getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DroneOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Output.internal_static_DroneOutput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Output.internal_static_DroneOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Output.DroneOutput.class, Output.DroneOutput.Builder.class);
    }

    public static com.google.protobuf.Parser<DroneOutput> PARSER =
        new com.google.protobuf.AbstractParser<DroneOutput>() {
      public DroneOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DroneOutput(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DroneOutput> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code DroneOutput.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TURN = 0;</code>
       */
      TURN(0, 0),
      /**
       * <code>FORWARD = 1;</code>
       */
      FORWARD(1, 1),
      /**
       * <code>LIFT = 2;</code>
       */
      LIFT(2, 2),
      /**
       * <code>LIFTOFF = 3;</code>
       */
      LIFTOFF(3, 3),
      /**
       * <code>LAND = 4;</code>
       */
      LAND(4, 4),
      /**
       * <code>FLIP = 5;</code>
       */
      FLIP(5, 5),
      ;

      /**
       * <code>TURN = 0;</code>
       */
      public static final int TURN_VALUE = 0;
      /**
       * <code>FORWARD = 1;</code>
       */
      public static final int FORWARD_VALUE = 1;
      /**
       * <code>LIFT = 2;</code>
       */
      public static final int LIFT_VALUE = 2;
      /**
       * <code>LIFTOFF = 3;</code>
       */
      public static final int LIFTOFF_VALUE = 3;
      /**
       * <code>LAND = 4;</code>
       */
      public static final int LAND_VALUE = 4;
      /**
       * <code>FLIP = 5;</code>
       */
      public static final int FLIP_VALUE = 5;


      public final int getNumber() { return value; }

      public static CommandType valueOf(int value) {
        switch (value) {
          case 0: return TURN;
          case 1: return FORWARD;
          case 2: return LIFT;
          case 3: return LIFTOFF;
          case 4: return LAND;
          case 5: return FLIP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Output.DroneOutput.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CommandType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DroneOutput.CommandType)
    }

    public interface CommandOrBuilder extends
        // @@protoc_insertion_point(interface_extends:DroneOutput.Command)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
       */
      java.util.List<Output.DroneOutput.CommandType> getCommandTypeList();
      /**
       * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
       */
      int getCommandTypeCount();
      /**
       * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
       */
      Output.DroneOutput.CommandType getCommandType(int index);

      /**
       * <code>optional float speed = 2;</code>
       *
       * <pre>
       * required
       * </pre>
       */
      boolean hasSpeed();
      /**
       * <code>optional float speed = 2;</code>
       *
       * <pre>
       * required
       * </pre>
       */
      float getSpeed();
    }
    /**
     * Protobuf type {@code DroneOutput.Command}
     */
    public static final class Command extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:DroneOutput.Command)
        CommandOrBuilder {
      // Use Command.newBuilder() to construct.
      private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Command defaultInstance;
      public static Command getDefaultInstance() {
        return defaultInstance;
      }

      public Command getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Command(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                Output.DroneOutput.CommandType value = Output.DroneOutput.CommandType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                  } else {
                  if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    commandType_ = new java.util.ArrayList<Output.DroneOutput.CommandType>();
                    mutable_bitField0_ |= 0x00000001;
                  }
                  commandType_.add(value);
                }
                break;
              }
              case 10: {
                int length = input.readRawVarint32();
                int oldLimit = input.pushLimit(length);
                while(input.getBytesUntilLimit() > 0) {
                  int rawValue = input.readEnum();
                  Output.DroneOutput.CommandType value = Output.DroneOutput.CommandType.valueOf(rawValue);
                  if (value == null) {
                    unknownFields.mergeVarintField(1, rawValue);
                    } else {
                    if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                      commandType_ = new java.util.ArrayList<Output.DroneOutput.CommandType>();
                      mutable_bitField0_ |= 0x00000001;
                    }
                    commandType_.add(value);
                  }
                }
                input.popLimit(oldLimit);
                break;
              }
              case 21: {
                bitField0_ |= 0x00000001;
                speed_ = input.readFloat();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            commandType_ = java.util.Collections.unmodifiableList(commandType_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Output.internal_static_DroneOutput_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Output.internal_static_DroneOutput_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Output.DroneOutput.Command.class, Output.DroneOutput.Command.Builder.class);
      }

      public static com.google.protobuf.Parser<Command> PARSER =
          new com.google.protobuf.AbstractParser<Command>() {
        public Command parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Command(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Command> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int COMMANDTYPE_FIELD_NUMBER = 1;
      private java.util.List<Output.DroneOutput.CommandType> commandType_;
      /**
       * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
       */
      public java.util.List<Output.DroneOutput.CommandType> getCommandTypeList() {
        return commandType_;
      }
      /**
       * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
       */
      public int getCommandTypeCount() {
        return commandType_.size();
      }
      /**
       * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
       */
      public Output.DroneOutput.CommandType getCommandType(int index) {
        return commandType_.get(index);
      }

      public static final int SPEED_FIELD_NUMBER = 2;
      private float speed_;
      /**
       * <code>optional float speed = 2;</code>
       *
       * <pre>
       * required
       * </pre>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional float speed = 2;</code>
       *
       * <pre>
       * required
       * </pre>
       */
      public float getSpeed() {
        return speed_;
      }

      private void initFields() {
        commandType_ = java.util.Collections.emptyList();
        speed_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < commandType_.size(); i++) {
          output.writeEnum(1, commandType_.get(i).getNumber());
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeFloat(2, speed_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < commandType_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeEnumSizeNoTag(commandType_.get(i).getNumber());
          }
          size += dataSize;
          size += 1 * commandType_.size();
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, speed_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Output.DroneOutput.Command parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Output.DroneOutput.Command parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Output.DroneOutput.Command parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Output.DroneOutput.Command parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Output.DroneOutput.Command parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Output.DroneOutput.Command parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Output.DroneOutput.Command parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Output.DroneOutput.Command parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Output.DroneOutput.Command parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Output.DroneOutput.Command parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Output.DroneOutput.Command prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code DroneOutput.Command}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:DroneOutput.Command)
          Output.DroneOutput.CommandOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Output.internal_static_DroneOutput_Command_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Output.internal_static_DroneOutput_Command_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Output.DroneOutput.Command.class, Output.DroneOutput.Command.Builder.class);
        }

        // Construct using Output.DroneOutput.Command.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          commandType_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          speed_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Output.internal_static_DroneOutput_Command_descriptor;
        }

        public Output.DroneOutput.Command getDefaultInstanceForType() {
          return Output.DroneOutput.Command.getDefaultInstance();
        }

        public Output.DroneOutput.Command build() {
          Output.DroneOutput.Command result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Output.DroneOutput.Command buildPartial() {
          Output.DroneOutput.Command result = new Output.DroneOutput.Command(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            commandType_ = java.util.Collections.unmodifiableList(commandType_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.commandType_ = commandType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000001;
          }
          result.speed_ = speed_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Output.DroneOutput.Command) {
            return mergeFrom((Output.DroneOutput.Command)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Output.DroneOutput.Command other) {
          if (other == Output.DroneOutput.Command.getDefaultInstance()) return this;
          if (!other.commandType_.isEmpty()) {
            if (commandType_.isEmpty()) {
              commandType_ = other.commandType_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCommandTypeIsMutable();
              commandType_.addAll(other.commandType_);
            }
            onChanged();
          }
          if (other.hasSpeed()) {
            setSpeed(other.getSpeed());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Output.DroneOutput.Command parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Output.DroneOutput.Command) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.util.List<Output.DroneOutput.CommandType> commandType_ =
          java.util.Collections.emptyList();
        private void ensureCommandTypeIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            commandType_ = new java.util.ArrayList<Output.DroneOutput.CommandType>(commandType_);
            bitField0_ |= 0x00000001;
          }
        }
        /**
         * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
         */
        public java.util.List<Output.DroneOutput.CommandType> getCommandTypeList() {
          return java.util.Collections.unmodifiableList(commandType_);
        }
        /**
         * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
         */
        public int getCommandTypeCount() {
          return commandType_.size();
        }
        /**
         * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
         */
        public Output.DroneOutput.CommandType getCommandType(int index) {
          return commandType_.get(index);
        }
        /**
         * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
         */
        public Builder setCommandType(
            int index, Output.DroneOutput.CommandType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandTypeIsMutable();
          commandType_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
         */
        public Builder addCommandType(Output.DroneOutput.CommandType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandTypeIsMutable();
          commandType_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
         */
        public Builder addAllCommandType(
            java.lang.Iterable<? extends Output.DroneOutput.CommandType> values) {
          ensureCommandTypeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, commandType_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated .DroneOutput.CommandType commandType = 1;</code>
         */
        public Builder clearCommandType() {
          commandType_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }

        private float speed_ ;
        /**
         * <code>optional float speed = 2;</code>
         *
         * <pre>
         * required
         * </pre>
         */
        public boolean hasSpeed() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional float speed = 2;</code>
         *
         * <pre>
         * required
         * </pre>
         */
        public float getSpeed() {
          return speed_;
        }
        /**
         * <code>optional float speed = 2;</code>
         *
         * <pre>
         * required
         * </pre>
         */
        public Builder setSpeed(float value) {
          bitField0_ |= 0x00000002;
          speed_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float speed = 2;</code>
         *
         * <pre>
         * required
         * </pre>
         */
        public Builder clearSpeed() {
          bitField0_ = (bitField0_ & ~0x00000002);
          speed_ = 0F;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:DroneOutput.Command)
      }

      static {
        defaultInstance = new Command(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:DroneOutput.Command)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Output.DroneOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Output.DroneOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Output.DroneOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Output.DroneOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Output.DroneOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Output.DroneOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Output.DroneOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Output.DroneOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Output.DroneOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Output.DroneOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Output.DroneOutput prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DroneOutput}
     *
     * <pre>
     * A message for controlling a A.R. Drone
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DroneOutput)
        Output.DroneOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Output.internal_static_DroneOutput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Output.internal_static_DroneOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Output.DroneOutput.class, Output.DroneOutput.Builder.class);
      }

      // Construct using Output.DroneOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Output.internal_static_DroneOutput_descriptor;
      }

      public Output.DroneOutput getDefaultInstanceForType() {
        return Output.DroneOutput.getDefaultInstance();
      }

      public Output.DroneOutput build() {
        Output.DroneOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Output.DroneOutput buildPartial() {
        Output.DroneOutput result = new Output.DroneOutput(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Output.DroneOutput) {
          return mergeFrom((Output.DroneOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Output.DroneOutput other) {
        if (other == Output.DroneOutput.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Output.DroneOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Output.DroneOutput) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DroneOutput)
    }

    static {
      defaultInstance = new DroneOutput(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DroneOutput)
  }

  public interface GameActionOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameActionOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float axes = 1;</code>
     */
    java.util.List<java.lang.Float> getAxesList();
    /**
     * <code>repeated float axes = 1;</code>
     */
    int getAxesCount();
    /**
     * <code>repeated float axes = 1;</code>
     */
    float getAxes(int index);

    /**
     * <code>repeated float rawData = 2;</code>
     */
    java.util.List<java.lang.Float> getRawDataList();
    /**
     * <code>repeated float rawData = 2;</code>
     */
    int getRawDataCount();
    /**
     * <code>repeated float rawData = 2;</code>
     */
    float getRawData(int index);
  }
  /**
   * Protobuf type {@code GameActionOutput}
   *
   * <pre>
   * A message for controlling a game action
   * </pre>
   */
  public static final class GameActionOutput extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GameActionOutput)
      GameActionOutputOrBuilder {
    // Use GameActionOutput.newBuilder() to construct.
    private GameActionOutput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameActionOutput(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameActionOutput defaultInstance;
    public static GameActionOutput getDefaultInstance() {
      return defaultInstance;
    }

    public GameActionOutput getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameActionOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                axes_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              axes_.add(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                axes_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                axes_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                rawData_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              rawData_.add(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                rawData_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                rawData_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          axes_ = java.util.Collections.unmodifiableList(axes_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          rawData_ = java.util.Collections.unmodifiableList(rawData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Output.internal_static_GameActionOutput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Output.internal_static_GameActionOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Output.GameActionOutput.class, Output.GameActionOutput.Builder.class);
    }

    public static com.google.protobuf.Parser<GameActionOutput> PARSER =
        new com.google.protobuf.AbstractParser<GameActionOutput>() {
      public GameActionOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameActionOutput(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameActionOutput> getParserForType() {
      return PARSER;
    }

    public static final int AXES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Float> axes_;
    /**
     * <code>repeated float axes = 1;</code>
     */
    public java.util.List<java.lang.Float>
        getAxesList() {
      return axes_;
    }
    /**
     * <code>repeated float axes = 1;</code>
     */
    public int getAxesCount() {
      return axes_.size();
    }
    /**
     * <code>repeated float axes = 1;</code>
     */
    public float getAxes(int index) {
      return axes_.get(index);
    }

    public static final int RAWDATA_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> rawData_;
    /**
     * <code>repeated float rawData = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getRawDataList() {
      return rawData_;
    }
    /**
     * <code>repeated float rawData = 2;</code>
     */
    public int getRawDataCount() {
      return rawData_.size();
    }
    /**
     * <code>repeated float rawData = 2;</code>
     */
    public float getRawData(int index) {
      return rawData_.get(index);
    }

    private void initFields() {
      axes_ = java.util.Collections.emptyList();
      rawData_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < axes_.size(); i++) {
        output.writeFloat(1, axes_.get(i));
      }
      for (int i = 0; i < rawData_.size(); i++) {
        output.writeFloat(2, rawData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getAxesList().size();
        size += dataSize;
        size += 1 * getAxesList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getRawDataList().size();
        size += dataSize;
        size += 1 * getRawDataList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Output.GameActionOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Output.GameActionOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Output.GameActionOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Output.GameActionOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Output.GameActionOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Output.GameActionOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Output.GameActionOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Output.GameActionOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Output.GameActionOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Output.GameActionOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Output.GameActionOutput prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameActionOutput}
     *
     * <pre>
     * A message for controlling a game action
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameActionOutput)
        Output.GameActionOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Output.internal_static_GameActionOutput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Output.internal_static_GameActionOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Output.GameActionOutput.class, Output.GameActionOutput.Builder.class);
      }

      // Construct using Output.GameActionOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        axes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        rawData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Output.internal_static_GameActionOutput_descriptor;
      }

      public Output.GameActionOutput getDefaultInstanceForType() {
        return Output.GameActionOutput.getDefaultInstance();
      }

      public Output.GameActionOutput build() {
        Output.GameActionOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Output.GameActionOutput buildPartial() {
        Output.GameActionOutput result = new Output.GameActionOutput(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          axes_ = java.util.Collections.unmodifiableList(axes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.axes_ = axes_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          rawData_ = java.util.Collections.unmodifiableList(rawData_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rawData_ = rawData_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Output.GameActionOutput) {
          return mergeFrom((Output.GameActionOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Output.GameActionOutput other) {
        if (other == Output.GameActionOutput.getDefaultInstance()) return this;
        if (!other.axes_.isEmpty()) {
          if (axes_.isEmpty()) {
            axes_ = other.axes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAxesIsMutable();
            axes_.addAll(other.axes_);
          }
          onChanged();
        }
        if (!other.rawData_.isEmpty()) {
          if (rawData_.isEmpty()) {
            rawData_ = other.rawData_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRawDataIsMutable();
            rawData_.addAll(other.rawData_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Output.GameActionOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Output.GameActionOutput) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Float> axes_ = java.util.Collections.emptyList();
      private void ensureAxesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          axes_ = new java.util.ArrayList<java.lang.Float>(axes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float axes = 1;</code>
       */
      public java.util.List<java.lang.Float>
          getAxesList() {
        return java.util.Collections.unmodifiableList(axes_);
      }
      /**
       * <code>repeated float axes = 1;</code>
       */
      public int getAxesCount() {
        return axes_.size();
      }
      /**
       * <code>repeated float axes = 1;</code>
       */
      public float getAxes(int index) {
        return axes_.get(index);
      }
      /**
       * <code>repeated float axes = 1;</code>
       */
      public Builder setAxes(
          int index, float value) {
        ensureAxesIsMutable();
        axes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float axes = 1;</code>
       */
      public Builder addAxes(float value) {
        ensureAxesIsMutable();
        axes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float axes = 1;</code>
       */
      public Builder addAllAxes(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureAxesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, axes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float axes = 1;</code>
       */
      public Builder clearAxes() {
        axes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> rawData_ = java.util.Collections.emptyList();
      private void ensureRawDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          rawData_ = new java.util.ArrayList<java.lang.Float>(rawData_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float rawData = 2;</code>
       */
      public java.util.List<java.lang.Float>
          getRawDataList() {
        return java.util.Collections.unmodifiableList(rawData_);
      }
      /**
       * <code>repeated float rawData = 2;</code>
       */
      public int getRawDataCount() {
        return rawData_.size();
      }
      /**
       * <code>repeated float rawData = 2;</code>
       */
      public float getRawData(int index) {
        return rawData_.get(index);
      }
      /**
       * <code>repeated float rawData = 2;</code>
       */
      public Builder setRawData(
          int index, float value) {
        ensureRawDataIsMutable();
        rawData_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float rawData = 2;</code>
       */
      public Builder addRawData(float value) {
        ensureRawDataIsMutable();
        rawData_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float rawData = 2;</code>
       */
      public Builder addAllRawData(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureRawDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rawData_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float rawData = 2;</code>
       */
      public Builder clearRawData() {
        rawData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GameActionOutput)
    }

    static {
      defaultInstance = new GameActionOutput(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GameActionOutput)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LEDOutput_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LEDOutput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DroneOutput_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DroneOutput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DroneOutput_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DroneOutput_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameActionOutput_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameActionOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014output.proto\"\027\n\tLEDOutput\022\n\n\002on\030\001 \001(\010\"" +
      "\247\001\n\013DroneOutput\032G\n\007Command\022-\n\013commandTyp" +
      "e\030\001 \003(\0162\030.DroneOutput.CommandType\022\r\n\005spe" +
      "ed\030\002 \001(\002\"O\n\013CommandType\022\010\n\004TURN\020\000\022\013\n\007FOR" +
      "WARD\020\001\022\010\n\004LIFT\020\002\022\013\n\007LIFTOFF\020\003\022\010\n\004LAND\020\004\022" +
      "\010\n\004FLIP\020\005\"1\n\020GameActionOutput\022\014\n\004axes\030\001 " +
      "\003(\002\022\017\n\007rawData\030\002 \003(\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LEDOutput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LEDOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LEDOutput_descriptor,
        new java.lang.String[] { "On", });
    internal_static_DroneOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DroneOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DroneOutput_descriptor,
        new java.lang.String[] { });
    internal_static_DroneOutput_Command_descriptor =
      internal_static_DroneOutput_descriptor.getNestedTypes().get(0);
    internal_static_DroneOutput_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DroneOutput_Command_descriptor,
        new java.lang.String[] { "CommandType", "Speed", });
    internal_static_GameActionOutput_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GameActionOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GameActionOutput_descriptor,
        new java.lang.String[] { "Axes", "RawData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
